### ISSUE TITLE
Parámetros query

### ISSUE THREAD

**Issue by siberiaaa** [G3-Graco/laboratorio-api-nice-team#7]
Cuando un controlador pide parámetros a través del query en algún endpoint, si no se inserta ningún dato, el fragmento en el middleware de `var idsesion = context.Request.Query["idsesion"].ToString();` guarda en la variable idsesion null,  como si yo no estuviese implementando en el método de ese endpoint que estoy pidiéndo por parámetros el parámetro del query 

O sea, básicamente si el usuario de la api decide no pasar ningún dato en el query, el código lo interpreta como si yo no estoy empleando el query porque está null y por ende no hace el proceso de validaciones en el query.

Hay alguna manera en la que pueda saber si se supone que algún método debía llevar en el query un dato? O también se me ocurrió como colocar un valor por defecto por ejemplo `post(int idsesion = -1)` , de modo que sin importar si al hacer la petición se ingresó un dato en el query correspondiente o no, el código identifique que había contenido en el query y lo valide...

**Comment by GGimenezG** [comment]
> O sea, básicamente si el usuario de la api decide no pasar ningún dato en el query, el código lo interpreta como si yo no estoy empleando el query porque está null y por ende no hace el proceso de validaciones en el query.

Ese no debería ser el comportamiento deseado?

Si el controlador pide un dato por query, el usuario no lo ingresa da como resultado `context.Request.Query["idsesion"].ToString();` igual a `null` para que el middleware valide tiene que existir ese parámetro en el query, si el usuario no lo ingresa, una de las primeras validaciones del servicio debe ser verificar que efectivamente el parámetro idsesion tenga algun valor mayor a 0 si no, mandar excepción para indicar que es un dato obligatorio.

> Hay alguna manera en la que pueda saber si se supone que algún método debía llevar en el query un dato? O también se me ocurrió como colocar un valor por defecto por ejemplo post(int idsesion = -1) , de modo que sin importar si al hacer la petición se ingresó un dato en el query correspondiente o no, el código identifique que había contenido en el query y lo valide...

esta me parece una buena aproximación, lo único es que si lo colocas a nivel del controlador, el middleware no lo va a validar, ya que este se aplica antes de entrar en el controlador por lo que estarás como en el primer caso.
